#!/usr/bin/env bash
declare -a buffer
declare -i line base
declare file version message

line=0
base=1
file="bed.txt"
version="INDEV"
message="🛏  Welcome to bed"

shopt -s checkwinsize; (:)
trap refresh WINCH ALRM
trap cleanup EXIT INT HUP USR1

startup() {
    cursor hide && cursor save
}

cleanup() {
    cursor show && cursor load
    exit
}

cursor() {
    case "$1" in
    #save) printf "\033[?47h";;
    #load) printf "\033[?47l";;
    hide) printf "\033[?25l";;
    show) printf "\033[?25h";;
    goto) printf "\033[%s;%sf" "$2" "$3";;
    *)    return 1;;
    esac
}

refresh() {
    clear
    printf "\e[100m %s (%s Lines) %s %sx%s %s \e[m\n" \
        "$file" "${#buffer[@]}" "$version" "$LINES" "$COLUMNS" "$base"
    for ((i=base; i-base < LINES-3; i++)); do
        ((i !=  line))        && printf "\e[90m"
        ((i > ${#buffer[@]})) && printf "   ~\e[m\n" || printf "%4s\e[m %s\n" "$i" "${buffer[i]}"
    done
    printf "\e[34m%s\e[m\n" "$message"
}

file_read() {
    file_set "$1" || return 1
    mapfile -t -O 1 buffer <"$file"
    line=1
}

file_set() {
    [ "$1" ] && file=$1 || return 1
}

file_write() {
    : >"$file"
    for line in "${buffer[@]}"; do echo "$line" >>"$file"; done
    return $?
}

line_up() {
    for ((i=0;i<$1;i++)); do
        ((line > 1))    && ((line--))
        ((line < base)) && ((base--))
        ((base <= 0))   && base=1
    done
}

line_down() {
    for ((i=0;i<$1;i++)); do
        ((line < ${#buffer[@]})) && ((line++))
        ((line > base+LINES-4))  && ((base++))
    done
}

line_delete() {
    buffer=([0]="" "${buffer[@]:1:line-1}" "${buffer[@]:line+1}")
    unset "buffer[0]"
    ((line > ${#buffer[@]})) && ((line--))
}

line_insert() {
    buffer=([0]="" "${buffer[@]:1:line}" "" "${buffer[@]:line+1}")
    unset "buffer[0]"
    ((line++))
    refresh
    line_edit
}

line_blank() {
    buffer=([0]="" "${buffer[@]:1:line}" "" "${buffer[@]:line+1}")
    unset "buffer[0]"
}

line_append() {
    cursor goto $((line-base + 2)) $((${#buffer[line]} + 6)) && cursor show
    read -re
    cursor hide
    buffer[line]+=$REPLY
}

line_edit() {
    cursor goto $((line-base + 2)) 6 && cursor show
    read -rei "${buffer[line]}"
    cursor hide
    buffer[line]=$REPLY
}

startup
file_read "$1"
refresh

declare -a key
while read -t0.02 -rsN1 key[0] || true; do
    # If a timeout occured, do nothing
    [ "${key[0]}" ] || continue

    # Nasty hack for multibyte input
    read -rsN1 -t 0.0001 key[1]
    read -rsN1 -t 0.0001 key[2]
    read -rsN1 -t 0.0001 key[3]

    # Compute key presses
    case "$(printf %s "${key[@]}")" in
    $'\e[A'|$'\e0A') line_up 1;;
    $'\e[B'|$'\e0B') line_down 1;;
    $'\e[5~'|$'\e05~') line_up $((LINES - 4));;
    $'\e[6~'|$'\e06~') line_down $((LINES - 4));;
    a) line_append;;
    b) line_blank;;
    c) line_clear;;
    d) line_delete;;
    e) line_edit;;
    f) file_set $(read -rep "> ");;
    i) line_insert;;
    l) file_read $(read -rep "> ");;
    q) exit;;
    w) file_write;;
    esac

    # Refresh the UI
    refresh
done
